<?php

namespace App\Controller\Admin;

use App\Entity\Address;
use App\Entity\Client;
use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\QueryBuilder;
use EasyCorp\Bundle\EasyAdminBundle\Collection\FieldCollection;
use EasyCorp\Bundle\EasyAdminBundle\Collection\FilterCollection;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Dto\EntityDto;
use EasyCorp\Bundle\EasyAdminBundle\Dto\SearchDto;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\EmailField;
use EasyCorp\Bundle\EasyAdminBundle\Field\FormField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TelephoneField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use Symfony\Component\Form\Form;

class ClientCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return Client::class;
    }

    public function configureFields(string $pageName): iterable
    {
        yield FormField::addPanel("Datos del cliente")
            ->collapsible();
        yield TextField::new('name')
            ->setColumns(6);
        yield TextField::new('cif', 'CIF')
            ->hideOnIndex()
            ->setColumns(2);
        yield EmailField::new('email')
            ->setColumns(6);
        yield TelephoneField::new('phone')
            ->setColumns(2);


        yield FormField::addPanel("Dirección")
            ->collapsible();;
        yield AssociationField::new('address');
        /*yield TextField::new('fullAddress', 'Dirección')
            ->hideOnForm();
        yield TextField::new('address.street', 'Dirección')
            ->setFormTypeOption()
            ->onlyOnForms();
        yield TextField::new('address.city', 'Ciudad')
            ->onlyOnForms();
        yield TextField::new('address.region', 'Provincia')
            ->onlyOnForms();
        yield TextField::new('address.postcode', 'Código postal')
            ->onlyOnForms();*/
    }

    public function createIndexQueryBuilder(SearchDto $searchDto, EntityDto $entityDto, FieldCollection $fields, FilterCollection $filters): QueryBuilder
    {
        //Clientes solo del usuario actual
        return parent::createIndexQueryBuilder($searchDto, $entityDto, $fields, $filters)
            ->andWhere('entity.user = :user')
            ->setParameter('user',$_SESSION['user_data']); // TODO: Change the autogenerated stub
    }

}
