<?php

namespace App\Controller\Admin;

use App\Entity\DeliveryNote;
use App\Repository\DeliveryNoteRepository;
use Doctrine\ORM\QueryBuilder;
use EasyCorp\Bundle\EasyAdminBundle\Collection\FieldCollection;
use EasyCorp\Bundle\EasyAdminBundle\Collection\FilterCollection;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Dto\EntityDto;
use EasyCorp\Bundle\EasyAdminBundle\Dto\SearchDto;
use EasyCorp\Bundle\EasyAdminBundle\Field\AssociationField;
use EasyCorp\Bundle\EasyAdminBundle\Field\BooleanField;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateField;
use EasyCorp\Bundle\EasyAdminBundle\Field\FormField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextareaField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
class DeliveryNoteCrudController extends AbstractCrudController
{
    public static function getEntityFqcn(): string
    {
        return DeliveryNote::class;
    }

    public function configureFields(string $pageName): iterable
    {
        //yield Field::new('client');
        yield FormField::addPanel('Detalles del Cliente');
        yield AssociationField::new('client', 'Cliente')
            ->autocomplete()
            ->setQueryBuilder(function (QueryBuilder $queryBuilder) {
                $queryBuilder->andWhere('entity.user = :user')
                    ->setParameter('user',$_SESSION['user_data']);
            });
        yield TextField::new('number', 'Nº Albarán')
            ->hideOnForm()
            ->setSortable(false) //quitar cuando solucione el TODO
            ->formatValue(static function ($value, ?DeliveryNote $dn){
                return $dn?->generateNumber();
            }); //TODO - Persistir el numero de albaran,a hora solo muestra xd
        yield FormField::addPanel('Detalles de la intervención');
        yield DateField::new('date', 'Fecha')
            ->setFormat('dd-MM-Y')
            ->setTextAlign('center');
        yield TextField::new('timeSpent', 'Tiempo empleado')
            ->hideOnIndex();
        yield TextareaField::new('material', 'Material entregado')
            ->hideOnIndex();
        yield TextareaField::new('faultDescription', 'Descripción de la avería')
            ->hideOnIndex();
        yield TextareaField::new('intervention', 'Intervención')
            ->hideOnIndex();
        yield BooleanField::new('signed', 'Firmado')
            ->hideOnForm()
            ->renderAsSwitch(false)
            ->setTextAlign('center');
        yield BooleanField::new('completed', 'Estado')
            ->hideOnForm()
            ->renderAsSwitch(false)
            ->setTextAlign('center');
        yield BooleanField::new('disabled', 'Anulado')
            ->hideOnForm()
            ->renderAsSwitch(false)
            ->setTextAlign('center');
    }

    //TODO - Poner acciones concretas de los albaranes
   /* public function configureActions(Actions $actions): Actions
    {
        return parent::configureActions($actions)
            //->add()
        ; // TODO: Change the autogenerated stub
    }*/

    public function configureCrud(Crud $crud): Crud
    {
        return parent::configureCrud($crud)
            ->setSearchFields(['date', 'client', 'number'])
            ->setPageTitle('new', 'Nuevo albarán')
            ->setPageTitle('index', 'Mis albaranes')
            ->setPageTitle('edit', 'Editar albarán')
            ->setPageTitle('detail', 'Detalles albarán');
    }

    public function createIndexQueryBuilder(SearchDto $searchDto, EntityDto $entityDto, FieldCollection $fields, FilterCollection $filters): QueryBuilder
    {
        //Albaranes solo del usuario actual
        return parent::createIndexQueryBuilder($searchDto, $entityDto, $fields, $filters)
            ->andWhere('entity.user = :user')
            ->setParameter('user',$_SESSION['user_data']); // TODO: Change the autogenerated stub
    }



}
